FROM node:14.15.0-alpine3.10 AS builder
WORKDIR /usr/src/
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build -- --prod

FROM nginx:1.18.0
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY startup.sh /docker-entrypoint.d/startup.sh
COPY --from=builder /usr/src/dist/webclient/ /opt/webclient/
