version: '2.1'
services:
  cms-db:
    image: 'mysql:5.6'
    volumes:
      - './xibo.sql:/docker-entrypoint-initdb.d/xibo.sql'
    environment:
      - 'MYSQL_DATABASE=cms'
      - 'MYSQL_USER=cms'
      - 'MYSQL_RANDOM_ROOT_PASSWORD=yes'
      - 'MYSQL_PASSWORD=password'
  cms-xmr:
    image: 'xibosignage/xibo-xmr:release-0.8'
    ports:
      - '9505:9505'
  cms-web:
    image: 'xibosignage/xibo-cms:release-2.3.7'
    links:
      - 'cms-db:mysql'
      - 'cms-xmr:50001'
    environment:
      - 'XMR_HOST=cms-xmr'
      - 'MYSQL_PASSWORD=password'
    ports:
      - '80:80'
  cms-quickchart:
    image: 'ianw/quickchart'
  identity-provider:
    image: 'jboss/keycloak:11.0.2'
    command: ['-b', '0.0.0.0', '-Dkeycloak.migration.action=import', '-Dkeycloak.profile.feature.upload_scripts=enabled', '-Dkeycloak.migration.provider=singleFile', '-Dkeycloak.migration.file=/tmp/dispway-realm.json']
    volumes:
      - './dispway-realm.json:/tmp/dispway-realm.json'
    environment:
      - 'KEYCLOAK_USER=dispway'
      - 'KEYCLOAK_PASSWORD=dispway'
      - 'DB_VENDOR=h2'
    ports:
      - '8080:8080'
